spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 154270847541-vqipt4jg0v9umma7qj1ivaoj0nvi1cdt.apps.googleusercontent.com
            clientSecret: b_z-NZ7PcwSvOs0-ROjgIk4w